### ISSUE TITLE
Call for collaborators!

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/wdio-allure-reporter#1]
Hi @just-boris, @dhoulker, @pazone.

I've only just discovered Allure, and have seen the thread you've started here: https://github.com/webdriverio/webdriverio/issues/532. I had a play with creating a basic reporter for v4.0 of Webdriverio, and it works great. 

I'd very much like your involvement in this project, to make an officially-supported reporter. As far as I can see, there's no need to couple it to Mocha - using the reporter system we have set up in the project, we should be able to get all the information we need from the BaseReporter without using Mocha hooks. This means it should work with any test framework!

A word of warning - v4.0 is not yet in beta, and some of the subprojects aren't fully published yet. So here's what I'm using:

- Use #framework branch of webdriverio: https://github.com/webdriverio/webdriverio/tree/framework
- symlink this repo as webdriverio/node_modules/wdio-allure-reporter
- symlink #junit branch of wdio-mocha-framework: https://github.com/webdriverio/wdio-mocha-framework/tree/junit as webdriverio/node_modules/wdio-mocha-framework
- Add the `allure` reporter in wdio.conf.js:
```js
		framework: 'mocha',
		reporter: ['allure']
```

If you have a chance, could you give that a try? I was able to get a decent looking report instantly.

I have a number of questions for you regarding the `allure-js-commons` library, and how to get the full features described in the Java annotations documentation. Let me know when you're ready for them!

**Comment by georgecrawford** [comment]
cc @klamping

**Comment by just-boris** [comment]
I pushed my initial work here: https://github.com/just-boris/wdio-allure-reporter

It can be moved when I will have got a working prototype. Since you are interested, I can take more time to work on it.

**Comment by georgecrawford** [comment]
Awesome. If you're happy, I'd like to merge any features of yours into mine, as the BaseReporter has now become a little more useful.

**Comment by pazone** [comment]
We are going to do it as soon as possible, thanks.

**Comment by klamping** [comment]
I'll be trying this out this week to see how it works for the set up at my work. Hope to help out with this however I can.

**Comment by georgecrawford** [comment]
I'll add some questions as they occur to me.

1. How are labels exposed in the Allure report? I can see them correctly added to my XML:
```xml
			<labels>
				<label name="specId" value="7ab016a71b4c3140e3a825217e668700"/>
				<label name="capabilities" value="chrome.latest.mac"/>
			</labels>
```
...but don't see them in the report anywhere. Is this not yet implemented?

**Comment by just-boris** [comment]
Labels are not designed for any custom values. It is a kind of container to store some internal Allure data.

Also, we have a public container named `<parameters></parameters>` but it has not implemented in JS-plugins. Once you have the following in your XML

```xml
<parameters>
    <parameter name="specId" value="7ab016a71b4c3140e3a825217e668700" kind="argument" />
    <parameter name="capabilities" value="chrome.latest.mac" kind="argument" />
</parameters>
```

You will see the following in the report:

![image](https://cloud.githubusercontent.com/assets/812240/11562023/4683a326-99dc-11e5-8c35-24b148367ac1.png)

**Comment by just-boris** [comment]
I created an issue for allure https://github.com/allure-framework/allure-js-commons/issues/8
I am going to implement this soon.

**Comment by georgecrawford** [comment]
Thanks - that sounds perfect.

**Comment by just-boris** [comment]
Ok, I did something that can work: https://github.com/just-boris/wdio-allure-reporter

Test code is [here](https://github.com/just-boris/wdio-allure-reporter/blob/master/test%2Fe2e%2Freporter.spec.js)

And then I got the following report

![image](https://cloud.githubusercontent.com/assets/812240/11721580/8839e6a6-9f75-11e5-892d-84bb629bb55a.png)

**Comment by just-boris** [comment]
Then I am going to implement steps, attachment features.

Also, you can see an issue here: I can't see a difference between failed assertions and unknown exceptions, so both of them are broken tests.

**Comment by georgecrawford** [comment]
I've got this far with my copy:
<img width="772" alt="screenshot 2015-12-10 16 47 17" src="https://cloud.githubusercontent.com/assets/84737/11721839/b560efc0-9f5d-11e5-9b92-19665c2e09fd.png">

It's using this repo, but the dependencies on webdriverio, wdio-mocha-framework and wdio-sync are quite complex. I'm currently using the following:
```
    "wdio-allure-reporter": "georgecrawford/wdio-allure-reporter#my-working-branch",
    "wdio-mocha-framework": "georgecrawford/wdio-mocha-framework#my-working-branch",
    "webdriverio": "georgecrawford/webdriverio#my-working-branch",
```
Want to try it out? We should be collaborating on the same repo if possible!

**Comment by just-boris** [comment]
@georgecrawford yes, we definitely should!

**Comment by christian-bromann** [comment]
@just-boris, @dhoulker, @pazone added you guys as collaborator to this repo

**Comment by georgecrawford** [comment]
My allure reporter is working great, but I have some work to do to get the required code into webdriverio v4.0. When that's done, I'd love some collaborator feedback from you guys.

**Comment by just-boris** [comment]
Well, we all team are on vacation now. I can take a look on it at the next week.

**Comment by christian-bromann** [comment]
I think we can close this now.
@just-boris feel free to reopen if you want though.
