### ISSUE TITLE
Cannot use allure.createStep with wdio-allure-reporter with cucumber framework?

### ISSUE THREAD

**Issue by sumeetp4** [webdriverio/wdio-allure-reporter#101]
When using wdio-allure-reporter with cucumber as framework

I'm not able to use allure.createStep like I could use with mocha-allure-reporter.

Also when I have defined a scenario in feature file and it has some Given-When-Then, it considers each Given-When-Then as a test case and scenario as a test suite in the html report.

Please check attached feature file and report screenshot

[feature.feature.txt](https://github.com/webdriverio/wdio-allure-reporter/files/1792152/feature.feature.txt)

Any help here @christian-bromann @just-boris 
![report](https://user-images.githubusercontent.com/29970107/37137879-cfdb282a-22cd-11e8-9cfa-2e354bd96325.png)

**Comment by BorisOsipov** [comment]
@sumeetp4 it will be available after https://github.com/webdriverio/wdio-allure-reporter/pull/96
stay tuned

**Comment by sumeetp4** [comment]
Sure @BorisOsipov ,looking forward to use it. Thanks :)
