### ISSUE TITLE
When multiple capabilities are configured in one Jenkins run, Allure report shows data for only one

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/wdio-allure-reporter#102]
When multiple capabilities are configured in one Jenkins run, Allure report shows data for only the last one.

E.g.: Allure report:
![image](https://user-images.githubusercontent.com/15637471/37159437-e30b3ad2-22bb-11e8-88b0-7167f75412a3.png)

vs. wdio.conf.js:

capabilities: [
           { browserName: 'firefox', marionette: true },          { browserName: 'chrome', chromeOptions: {
            prefs: {'credentials_enable_service': false, 'profile': {'password_manager_enabled': false}},
            args: ['--start-maximized', '--disable-cache', '--disable-application-cache',
                '--disable-offline-load-stale-cache', '--disk-cache-size=0',
                '--v8-cache-options=off', '--disable-infobars']
        }},
        { browserName: 'safari', AllowRemoteAutomation: true },   // Allow Remote Automation via 
          { browserName: 'internet explorer', "version" : '10'},
         { browserName: 'internet explorer', "version" : '11'},
    ],

Environment
WebdriverIO version: 1.0.3
Node.js version: 6.5.0
Standalone
wdio-cucumber-framework ^1.1.0"
*wdio-allure-reporter 0.3.2
allure-js-commons@1.3.1 (installed with wdio-allure-reporter)

**Comment by BorisOsipov** [comment]
duplicate https://github.com/webdriverio/wdio-allure-reporter/issues/52

**Comment by BorisOsipov** [comment]
@osmolyar I understood your concern. I guess we can start disscusion how we can handle this case before we will be able to migrate to allure2 completly.
