### ISSUE TITLE
Report title been places in wrong position

### ISSUE THREAD

**Issue by ezwanharun** [webdriverio/wdio-allure-reporter#105]
hi all, 

I noticed that the allure report that been generated is showing the wrong scenario and feature title. Look like the 'Feature' and 'Scenario' title tagging is been put on the same layer which is on 'Feature' layer. I attached the image on how my report look like. This cause all my steps been drag forwards and act as scenarios /test cases now. 

![screen shot 2018-03-14 at 12 17 04 pm](https://user-images.githubusercontent.com/13920802/37383137-b0138880-2781-11e8-8810-c9ee627419fc.png)

_config.js_
`
reporters: ['allure'],
    reporterOptions: {
        allure: { 
            outputDir: './webdriverIO/allure-results/',
            disableWebdriverStepsReporting: true
        }
    }
`

_package.json_
` 
"wdio-allure-reporter": "^0.5.0",
    "wdio-appium-service": "^0.2.3",
    "wdio-cucumber-framework": "^1.1.0",
    "wdio-jasmine-framework": "^0.2.2",
    "webdriverio": "^4.8.0",
    "cucumber": "^4.0.0",
    "allure-commandline": "^2.5.0",
`
![screen shot 2018-03-14 at 12 33 23 pm](https://user-images.githubusercontent.com/13920802/37383478-ee1a4b58-2783-11e8-9b87-47b2cade73e4.png)

**Comment by BorisOsipov** [comment]
@ezwanharun 
Yes it is.
It will be fixed in https://github.com/webdriverio/wdio-allure-reporter/issues/97

**Comment by BorisOsipov** [comment]
>This cause all my steps been drag forwards and act as scenarios /test cases now.

it was fixed. See https://github.com/webdriverio/wdio-allure-reporter/issues/97 for details.

Looking forward for your feedback.
