### ISSUE TITLE
latest version of wdio-allure-reporter" does not generate allure report

### ISSUE THREAD

**Issue by amiya-pattnaik** [webdriverio/wdio-allure-reporter#109]
Hi,
I noticed that that after upgrading the wdio-allure-reporter": "^0.6.0", it does not generate the report.
`allure generate ./allure-results -c  && allure open report `, opens a blank report.
below are the modules used.
wdio-allure-reporter": "^0.6.0",
"allure-commandline": "^2.5.0",
"wdio-mocha-framework": "^0.2.2",

![image](https://user-images.githubusercontent.com/10468789/37562412-786b53a2-2a35-11e8-882a-2d99393d091e.png)

Please note , it noticed that, now the ./allure-results contains number of .json file and .xml file for each suite, compare to earlier number of .txt file etc.

Thanks,
Amiya

**Comment by BorisOsipov** [comment]
Works fine in sample project https://github.com/BorisOsipov/wdio-allure-multibrowser-test

Please double check out setup. If you have simple project to reproduce the issue share it with us.

P.S.
>now the ./allure-results contains number of .json file and .xml file for each suite, compare to earlier number of .txt file etc.

It always generates xml files for reporting. Nothing changed here.

**Comment by amiya-pattnaik** [comment]
Hi Boris,
thanks for your information. I found the root cause. the newer version of allure has command `allure open`  instead of earlier version which used to be `allure open report`. Now it is working with `allure open`. 

Thanks for your advise.
