### ISSUE TITLE
Can I use createStep function of mocha-allure-reporter in wdio-allure reporter?

### ISSUE THREAD

**Issue by sumeetp4** [webdriverio/wdio-allure-reporter#112]
I am running Cucumber scripts using wdio.conf

I see that createStep function is added in wdio-allure-reporter to add custom steps, but it is different from the one in mocha-allure reporter API where we used to pass the name and stepfunc  (where Result of each call of this function will be recorded into report)

But in wdio-allure-reporter I see that createStep function is defined as createStep(title, body, [bodyLabel])
which takes title and body. So how I do get the result of the step here. It is coming as unknown in the screenshot below

![allure](https://user-images.githubusercontent.com/29970107/38301905-8e8c0eb4-381e-11e8-813d-5819e934dfe1.png)

Can I use the createStep function that is defined in mocha-allure-reporter API?

any help @BorisOsipov

**Comment by BorisOsipov** [comment]
@sumeetp4  thanks for reporting this

> It is coming as unknown in the screenshot below
It is a bug. But we don't know real step status and I don't know how fix it now.

>Can I use the createStep function that is defined in mocha-allure-reporter API?
No

**Comment by sumeetp4** [comment]
Oh okay. Thanks @BorisOsipov

**Comment by BorisOsipov** [comment]
Unknown step status was fixed in https://github.com/webdriverio/wdio-allure-reporter/pull/113
No you can specify step status createStep(title, body, [bodyLabel], [status]) or keep default 'passed'

**Comment by sumeetp4** [comment]
Cool. Thanks @BorisOsipov
