### ISSUE TITLE
No such file or directory ./AllureCommandline/bin/allure

### ISSUE THREAD

**Issue by wendywww** [webdriverio/wdio-allure-reporter#114]
In experiment on wdio-allure reporter on jenkins. 
**Encountered such error:** 
/home/ec2-user/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/AllureCommandline/bin/allure generate -c -o /home/ec2-user/workspace/integration-tests-allure/allure-report

env: '/home/ec2-user/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/AllureCommandline/bin/allure': No such file or directory

**Under wdio.config**
 reporters: ['dot', 'spec', 'junit', 'allure'],
  reporterOptions: {
    junit: {
      outputDir: process.env.CIRCLE_TEST_REPORTS ? `${process.env.CIRCLE_TEST_REPORTS}/webdriverio/` : './logs/',
    },
    allure: {
      outputDir: './allure-results'
    }

package-lock.json
  "wdio-allure-reporter": {
      _"version": "0.6.0",_
      "resolved": "https://registry.npmjs.org/wdio-allure-reporter/-/wdio-allure-reporter-0.6.0.tgz",
      "integrity": "sha512-EMeNuCjrvL2qPzOHDomb3sfdNINC2RuaK4v80i8Lj1TZT08HMHZYqJbqxWsxrLH0py1LN1cOwKxzSUT++P5U/w==",
      "dev": true,
      "requires": {
        "allure-js-commons": "1.3.1",
        "babel-runtime": "6.26.0"
      },

package.json 
"devDependencies": "wdio-allure-reporter": _"^0.6.1"_

jenkins file for pipline script:
post {
                always {
                    archiveArtifacts allowEmptyArchive: true, artifacts: 'integration/logs/*.*'
                    archiveArtifacts allowEmptyArchive: true, artifacts: 'integration/shots/*.*'
                    junit 'integration/logs/*.xml'
                    _allure([includeProperties: false, jdk: '', properties: [[key: 'variant', value: '${VARIANT}']], reportBuildPolicy: 'ALWAYS',results: [[path: 'allure-results']]])_ 
                    cleanWs()
                }
            }

**Comment by wendywww** [comment]
![screen shot 2018-04-30 at 11 46 03 am](https://user-images.githubusercontent.com/5750536/39449304-876ddf96-4c7c-11e8-9254-8f8b80fe46e7.png)

**Comment by BorisOsipov** [comment]
Hi @wendywww 

It isn't wdio-alure-reporter issue.
You may ask for help in allure-framework gitter
https://gitter.im/allure-framework/allure-core

or create issue in allure-jenkins plugin repo (don't know link).

**Comment by wendywww** [comment]
Ok, thank you.
