### ISSUE TITLE
Feature Request - Adding Issue link and Severity level

### ISSUE THREAD

**Issue by perwez123** [webdriverio/wdio-allure-reporter#119]
I have used the allure report for TestNg and Spock framework where I have used all the API of allure such as (feature, story, description, severity, issue, testId, host). There are many feature which is  missing such as **(severity, issue, testId, host, reportName)** in wdio-allure-reporter. 

I feel these features are very interesting and all will love to have it supported by wdio-allure-reporter.

Can we expect this features to release any time sooner?

**Comment by BorisOsipov** [comment]
@perwez123 yes it isn't hard to support.

Feel free to submit PR.

**Comment by thespecial** [comment]
@perwez123 @BorisOsipov i've submitted PR about adding severity -- https://github.com/webdriverio/wdio-allure-reporter/pull/126 . 

Could someone review and merge if ok, please?

**Comment by BorisOsipov** [comment]
@thespecial thanks! awesome 👍
