### ISSUE TITLE
History shows up in the Retries tab

### ISSUE THREAD

**Issue by javacoldbrew** [webdriverio/wdio-allure-reporter#120]
<img width="397" alt="allurereportsretries" src="https://user-images.githubusercontent.com/25971275/40925388-9dbf6d60-67e7-11e8-844f-62ed8d1dd4be.PNG">
<img width="409" alt="allurereportshistory" src="https://user-images.githubusercontent.com/25971275/40925392-a0c594a8-67e7-11e8-9a3f-89878daee2d0.PNG">

In `wdio.conf.js` I have reporter options like this:
```
   // Test reporter for stdout.
   // The only one supported by default is 'dot'
  // see also: http://webdriver.io/guide/reporters/dot.html
  reporters: ['allure', 'cucumber'], //['allure', 'cucumber', 'dot', 'spec'],
  reporterOptions: {
    allure: {
      outputDir: './reports/allure-data',
      disableWebdriverStepsReporting: true,
      disableWebdriverScreenshotsReporting: false,
      useCucumberStepReporter: true
    }
  },
```

**Comment by christian-bromann** [comment]
I am not sure if the history was part of the webdriverio report. I think it was always blank like this.

**Comment by BorisOsipov** [comment]
It isn't wdio-allure-reporter issue. In retries tab you see retries(cuz you don't clear allure-results and add test with the same name to report scope). As I know history generation requires additional steps(google it) and it may requere allure2 format (we use allure1)

**Comment by baev** [comment]
> it may requere allure2 format (we use allure1)

history feature is format independent, here you can find short note about history and other features your can add to the report https://stackoverflow.com/a/46222758/3915166

**Comment by javacoldbrew** [comment]
Thank you all for your help!

@baev Thank you for the link, that helped clear up a lot of things!
