### ISSUE TITLE
wdio allure reporter is not displaying all the executed steps of Scenario Outline and the steps displayed are not in the right order

### ISSUE THREAD

**Issue by PavanGurramQA** [webdriverio/wdio-allure-reporter#122]
Hi All,

I really need someone's help to resolve the below issues. Any help is really appreciated!!

1.  To describe with an example, my scenario outline has 7 steps and with 2 examples. When it is executed, expecting the total number of executed steps count should be 14 but it is showing as 9 i.e., only the unique steps but not all the steps although they are executed. Since my test suite is large, there is a huge difference in the executed steps count than expected. Screenshots of Scenario Outline and Allure report are attached.

![image](https://user-images.githubusercontent.com/36418052/41296199-52f9124a-6e54-11e8-980e-1402d3c86e30.png)
![image](https://user-images.githubusercontent.com/36418052/41296249-734533e4-6e54-11e8-8aa1-9a0c8635111a.png)
![image](https://user-images.githubusercontent.com/36418052/41296275-7e495ef0-6e54-11e8-9dac-80c2f3f5c9b9.png)

2. As you can see in the screnshots, executed steps are NOT in the order of the steps which are written in scenario outline.

I'm using below configurations. I've got stuck at this point and not able to proceed further and it is very critical for us to resolve it. Please HELP.

Node v6.12.0
NPM v3.10.10
"wdio-allure-reporter": "^0.6.2"

Kindly let me know for any more details. Thanks.

**Comment by BorisOsipov** [comment]
@PavanGurramQA Allure handles two scenarios with the same names as retries of the one scenario.
Change your scenario names to make it different for allure
e.g. add params from the examples section to the name
`Scenario Outline: 1 person basic search <param1name> <param2name>`

I guess it will solve both issues.
If it is not - attach your source allure xml file.

**Comment by PavanGurramQA** [comment]
@BorisOsipov Many many thanks for your prompt response. Applied your suggestion and the issue got resolved. Really appreciate your response :)
