### ISSUE TITLE
Allure report is not opening in Chrome/IE

### ISSUE THREAD

**Issue by PavanGurramQA** [webdriverio/wdio-allure-reporter#123]
Hi All,

I have gone through one of the sites which talk about the solution to make Allure report open in Chrome browser. Unfortunately, the solution wasn't clear and now raising it as a new issue. Please route me to any existing issue if raised for the same.

As the issue title says, Allure report is NOT opening in Chrome and IE browser (screenshot attached) and working fine with Firefox browser. Json files are created perfectly.

I want the report to be opened in both IE and Chrome as these are the default browsers used in our machines. Please help. Thanks in advance.

**Comment by BorisOsipov** [comment]
It isn't allure wdio reporter issue, please use [allure-gitter-channel](https://gitter.im/allure-framework/allure-core) for such questions.

For your question see -
https://github.com/allure-framework/allure1/wiki/FAQ-and-Troubleshooting#i-see-nothing-when-opening-the-report-page-in-my-browser--access-denied-message

**Comment by PavanGurramQA** [comment]
Thanks @BorisOsipov. I'll go through the link you provided for my question. I'll use the allure-gitter-channel for any questions. Cheers!!
