### ISSUE TITLE
"before each", "after each", "after all" hooks reported as broken when using Mocha framework

### ISSUE THREAD

**Issue by nzhenry** [webdriverio/wdio-allure-reporter#13]
When using the Mocha framework with webdriver.io and wdio-allure-reporter, the xml output (eg "./allure-results/ce079369-cea8-4359-87c2-a054b576523b-testsuite.xml") always contains 3 failures: "before each hook", "after each hook" and "after all hook".

Download [example.zip](https://github.com/webdriverio/wdio-allure-reporter/files/280863/example.zip) to reproduce.

**Comment by christian-bromann** [comment]
@nzhenry we are currently rewriting the reporter and it will be fixed with that

__cc__ @gronke
