### ISSUE TITLE
Before, after hook shown as broken in Allure report

### ISSUE THREAD

**Issue by anarwal** [webdriverio/wdio-allure-reporter#14]
When a test is run, even though there are not failures or broken tests, but before and after hooks are shown as broken in test report.

**Comment by anarwal** [comment]
![failedtest](https://cloud.githubusercontent.com/assets/15256209/15552156/0ea5aa42-226e-11e6-807f-da5f71c72d1a.PNG)

**Comment by christian-bromann** [comment]
@gronke is this still the case in your branch?
@anarwal can you say which framework you are using?

**Comment by anarwal** [comment]
I am using mocha

**Comment by anarwal** [comment]
My package.json look like this
```
 "allure-commandline": "^1.4.22-1",
    "chai": "^3.4.1",
    "gulp": "^3.9.0",
    "gulp-shell": "^0.5.1",
    "mocha": "^2.3.4",
    "moment": "^2.10.6",
    "wdio-allure-reporter": "0.0.2",
    "wdio-junit-reporter": "0.0.2",
    "wdio-mocha-framework": "^0.2.9",
    "wdio-selenium-standalone-service": "0.0.3",
    "webdriverio": "^4.0.7"
```

**Comment by anarwal** [comment]
any of the versions I need to update?

**Comment by gronke** [comment]
@christian-bromann no, in in #8 only failing hooks will show up (marked as broken)

**Comment by christian-bromann** [comment]
Sweet, @anarwal please wait until we merged and released that PR change.

**Comment by anarwal** [comment]
@gronke Did you push the changes yet for this defect to master?

**Comment by christian-bromann** [comment]
No, there are still PR open
