### ISSUE TITLE
Trends are dead.

### ISSUE THREAD

**Issue by KiT-Maverik** [webdriverio/wdio-allure-reporter#153]
Hey everyone!
My tests aren't collecting historical data. All trend tabs show "There is nothing to show". I'm saving allure results in the same folder. But still, trends are dead. Can you advise me how can I fix this issue?
wdio+mocha+wdio-allure-reporter

**Comment by BorisOsipov** [comment]
Hi @KiT-Maverik 
It is not issue\question related to reporter. It is allure report generation features.
Read docs or SO answers e.g. https://stackoverflow.com/a/50143515
Or ask for help in allure gitter https://gitter.im/allure-framework/allure-core

**Comment by KiT-Maverik** [comment]
Thanks @BorisOsipov
