### ISSUE TITLE
Test are not included in the report when the Before hook fails

### ISSUE THREAD

**Issue by raulcabero** [webdriverio/wdio-allure-reporter#154]
I have code to log in to my application in the before hook , when the log in fails in my report I am only see the before and after execution and not the execution of my tests, I was expecting to see the my tests are listed in the report as failed.

this is my wdio.conf configutaion:

`{
	specs: [
		'./test/spec/**/*.js'
	],
	maxInstances: 10,
	capabilities: [{
		maxInstances: 1,
		browserName: '',
	}],
	sync: true,
	logLevel: 'info',
	logOutput: './wdioLogs/',
	outputDir: './wdioLogs/',
	coloredLogs: true,
	deprecationWarnings: false,
	bail: 0,
	screenshotPath: './errorShots/',
	baseUrl: '',
	waitforTimeout: 10000,
	connectionRetryTimeout: 90000,
	connectionRetryCount: 3,
	services: ['selenium-standalone'],
	framework: 'mocha',
	reporters: ['spec', ['allure', {
		disableWebdriverScreenshotsReporting: false,
	}]],
	mochaOpts: {
		ui: 'bdd',
		timeout: 600000
	},
}`

I am using webdriverIO 5.7.8 and @wdio/allure-reporter 5.7.8

**Comment by BorisOsipov** [comment]
@raulcabero 

First, all v5 reporter issues should be reported in monorepo v5 https://github.com/webdriverio/webdriverio/issues/new/choose

Second, 
> I am only see the before and after execution and not the execution of my tests, I was expecting to see the my tests are listed in the report as failed.

It is because mocha doesn't run tests if before hook failed. So we don't have any info about what tests do you have.
