### ISSUE TITLE
Categories issue

### ISSUE THREAD

**Issue by KiT-Maverik** [webdriverio/wdio-allure-reporter#157]
hey guys!
I can't assign specific TC's to categories. Can you assist?
XML-file
[sample.txt](https://github.com/webdriverio-boneyard/wdio-allure-reporter/files/3090049/sample.txt)

category entity from categories.json file
 {
    "name": "new one",
    "matchedStatuses": ["broken"],
    "messageRegex": "unknown error: Element .* is not clickable at point .* Other element would receive the click: .*"
  },

**Comment by BorisOsipov** [comment]
@KiT-Maverik it is out of reporter scope

**Comment by BorisOsipov** [comment]
Asks in gitter https://gitter.im/allure-framework/allure-core
