### ISSUE TITLE
"POST" entries appearing on test report

### ISSUE THREAD

**Issue by adamsjoe** [webdriverio/wdio-allure-reporter#160]
Hi,
when I view my test report, I am now seeing lots of "POST" entries (example ("POST /session/:sessionId/window/maximize") - I recently upgraded versions and previously this wasn't shown.

Accoring to my packages.json file I am using the following:
    "@wdio/allure-reporter": "^5.7.0",
    "@wdio/cli": "^5.7.0",
    "@wdio/local-runner": "^5.7.0",
    "@wdio/mocha-framework": "^5.7.0",

has anyone else seen this?

**Comment by BorisOsipov** [comment]
@adamsjoe it is repo for wdio-allure v4 only. Submit issue to main repo for v5 version https://github.com/webdriverio/webdriverio/issues/new?template=--bug-report.md

Also first please check your configuration using docs here
https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-allure-reporter#configuration
