### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by alexcason** [webdriverio/wdio-allure-reporter#2]
I'm attempting to integrate this reporter into a test project based upon webdriverio/cucumber-boilerplate.

So far I've included this repository as a module in the project, built the `build/reporter.js` file and added the `main` attribute to `package.json` pointing to it. I've then referenced the module in the config file of my test project and set it as the reporter.

    var AllureReporter = require('wdio-allure-reporter');

    exports.config = {

        ...

        reporter: AllureReporter,
        reporterOptions: {
            outputDir: './'
        },

        ...

    };

When I run the tests the cases execute as normal but nothing related to the reporter seems to be happening. I've added debug logging to the `reporter.js` file and it doesn't seem to be executing.

Am I doing something wrong? Is it possible to get a quick getting started guide?

Thanks for your help.

**Comment by just-boris** [comment]
Hello! Why did you close this?

I just have started working on guide yesterday. I am going to create a repo with demo project and write few words about it.

**Comment by alexcason** [comment]
Hi @just-boris,

I closed the issue as I resolved the specific problem I was having integrating a custom reporter with the cucumber-boilerplate project.

A getting started guide would still be very useful. I can edit the initial issue to remove the reference to the specific issue which I solved if you want to tag the guide against this issue?

**Comment by just-boris** [comment]
Okay. I will create the new one, when I will have something to show.
