### ISSUE TITLE
integration tests failing

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/wdio-allure-reporter#23]
@gronke @just-boris for some reason the tests started failing. I didn't do any major changes but improved the test setup and made some code refactorings. Can you guys check why 4 of these tests are failing?

See https://travis-ci.org/webdriverio/wdio-allure-reporter

**Comment by just-boris** [comment]
Will look at it this evening. By the way, this is the case when `FULL_OUTPUT` option may help.

**Comment by just-boris** [comment]
Something has changed in events flow. I guess you have updated dependencies, and mocha-frameworks now fires events differently than before.

For, example for testcase `should report failed before-all hook` now our before hook are not considered as failed, and test is still run however it should not. I tried to return rejected promise instead of throwing error, and then it works.

I think there is an issue in wdio-mocha-framework or maybe mocha itself regarding synchronous exception handling.

I will come later with more detailed bug report.

**Comment by just-boris** [comment]
I believe that this failure can be fixed when this will be merged: https://github.com/webdriverio/wdio-sync/pull/35

**Comment by christian-bromann** [comment]
@just-boris I updated the framework adapter and bumped the deps in this project. Seems it has fixed almost all issues. Still [this](https://github.com/webdriverio/wdio-allure-reporter/blob/master/test/specs/test-case.js#L19-L32) test still seems to be broken due to last assertion.

**Comment by just-boris** [comment]
Surprisingly this test is passing for me.

However it shouldn't because the result XML is invalid. It contains unresolved step:

```xml
<step start="1467669446601" stop="" status="">
  <name>GET /wd/hub/session/4b609e40-4232-11e6-b400-0107491a845e/screenshot</name>
  <title>GET /wd/hub/session/4b609e40-4232-11e6-b400-0107491a845e/screenshot</title>
  <attachments></attachments>
  <steps></steps>
</step>
```

I logged all events that is fired by BaseReporter and found the following:

```
runner:start
runner:command
runner:init
runner:result
hook:start
hook:end
suite:start
test:start
hook:start
hook:end
runner:command
runner:result
runner:command <- here we are clicking on non-existing element
test:fail
test:end
runner:command <- taking screenshot because of failied test
hook:start
hook:end
suite:end  <- end suite. Allure can't update test data after suite has been finished.
hook:start
hook:end
runner:command <- the resulting failing screenshot. Goes to /dev/null, because Allure already finished its job
runner:result
runner:screenshot
runner:result
runner:end
```

I think that the `suite:end` event should be fired only when all commands are done. Then everything will be fine here.

**Comment by christian-bromann** [comment]
> I think that the suite:end event should be fired only when all commands are done.

what do you mean by that?

**Comment by just-boris** [comment]
That we should make test wait until screenshot command will be finished.

**Comment by gronke** [comment]
To workaround this (and similar issues) I had to store the last executed test and suites (the "stack"). When `suite:end` is fired we don't know if there are any hooks running. The only point in time where we can be sure a test is finished with all hooks is when the next `suite:start` fires.

My first thought was to change the event order in BaseReporter, but it makes sense to run an after hook, **after** a suite ended. (Btw. that applies to before hooks too)

Tweaking the screenshot test case would not solve the problem. The only thing we could do without keeping track of the stack is to add a delay. The hardcoded delay would have to be long enough to be sure the screenshot was saved successfully, but also not so long that the test times out. Probably not an acceptable solution for us.

The issue can occur (at least) in this stages:
- before-all
- screenshot
- after-all

**Comment by just-boris** [comment]
First of all, I believe that incorrect events order is a bug, not feature. I am going to check out [the reject function](https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L172) logic. Its code looks like it should work as I expected, but it doesn't.

As another effect of this issue, you can see that request to delete session is being sent before the response with screenshot has arrived.

@gronke could you please elaborate more about the issue with before-all/after-all? For now, I don't see anything wrong here.

**Comment by netmajor** [comment]
I think that issue is outdated for now... All tests passed

**Comment by christian-bromann** [comment]
Tests to master passing again ... closing
