### ISSUE TITLE
Stop track command results if session has ended

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/wdio-allure-reporter#24]
see webdriverio/webdriverio#1432

**Comment by just-boris** [comment]
This is similar with the issue, that I am investigating there: https://github.com/webdriverio/wdio-allure-reporter/issues/23#issuecomment-230358883

I will add a test case for to check `waitForExist` behavior as well.

As quick fix I can suggest not to listen to `runner:command` events at all, but record only finished commands at `runner:result`. We will loose some steps, but at least it would work.

By the way, do we have an event to capture failed commands? Now we just mark last step as failed on `test:fail`, but sometimes this is not true.

**Comment by christian-bromann** [comment]
> We will loose some steps, but at least it would work.

Sounds good to me

> By the way, do we have an event to capture failed commands?

I don't think so but we have an event that gets triggered if a command has finished and contains an error if it failed

**Comment by just-boris** [comment]
I found the only [`result` event](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/RequestHandler.js#L155) so far, which is called only in case of success.

**Comment by just-boris** [comment]
Finally I finished work on https://github.com/webdriverio/webdriverio/issues/1461 It seems to fix this issue and maybe some more. Now I am waiting for your feedback @christian-bromann

**Comment by christian-bromann** [comment]
thanks @just-boris
