### ISSUE TITLE
screenshot attachment

### ISSUE THREAD

**Issue by evrycollin** [webdriverio/wdio-allure-reporter#25]
it would be nice for the reporter to listen on 'runner:screenshot' event in order for testcase to be able to attach screenshot with a simple standard webdriverio command :

`browser.emit('screenshot', {filename: elmtImg, data: fs.readFileSync(elmtImg, {encoding: 'base64'}) } );`

Code to implement this fix :

`this.on('runner:screenshot', function (command) {
            var allure = _this.getAllure(command.cid);
            allure.addAttachment('screenshot '+command.filename, new Buffer(command.data, 'base64'));
        });`

**Comment by just-boris** [comment]
Hello!

It would make sense unless we are already saving all screenshots with [the following code](https://github.com/webdriverio/wdio-allure-reporter/blob/master/lib/reporter.js#L95). If you have an issue, when screenshot is not saved, provide a code example, then I will try to help you.

**Comment by GeoffreyBooth** [comment]
@just-boris I would like to arbitrarily attach strings or files to steps. In my particular use case, I have a hook that runs after every step, and if that step failed it retrieves the browser and server logs. I would like to be able to attach these strings to a step, either as strings or as files.

Is there any way to call `allure.addAttachment` from within a hook function? Or is there an event I can emit that can percolate up to `wdio-allure-reporter` that I can pass a string or blob or filename to, that it will call `allure.addAttachment` for?

**Comment by just-boris** [comment]
You do not have access to `allure` object using wdio-allure-reporter, due to multiprocess architecture.

Likely, some steps towards this will be done in https://github.com/webdriverio/wdio-allure-reporter/issues/37

**Comment by GeoffreyBooth** [comment]
@just-boris Until the new versions come out and hopefully solve this, is there a workaround that works today? I have access to write to the `allure-report` folder, can’t I just save my attachment there directly? How do I get the GUID that Allure expects in the filename, and is there anything I need to update in an XML file or elsewhere?

**Comment by just-boris** [comment]
Current model of interaction between Webdriver.io and Allure doesn't give any chance to change anything there.
You can either use `allure-mocha-reporter`, however, it doesn't work with parallel tests and requires more manual setup from you.
Second option will be an attempt to implement the feature here. I planned to have this working via `process.send` calls. Somehow like this

```js
process.send({
  event: 'allure:attachment',
  name: 'Test attachment',
  content: 'attachment content'
});
```

reporter will be able to catch these events with the following code

```js
this.on('allure:attachment', (event) => {
  allure.getCurrentTest().addAttachment(event.name, event.content);
});
```

These two changes will be basically enough to have this working, but this should be more tested, of course.

**Comment by GeoffreyBooth** [comment]
@just-boris I implemented your comment in https://github.com/webdriverio/wdio-allure-reporter/pull/39

**Comment by Burgi0101** [comment]
Hey guys I am not quite sure if you already checked the wdio-allure-addons-reporter which is attaching screenshots to the tests automatically!
Have to admit I didn't check how he is doing it but it's working!

https://www.npmjs.com/package/wdio-allure-addons-reporter

**Comment by christian-bromann** [comment]
@Burgi0101 this project is published by the author of this issue @evrycollin 

@evrycollin would you consider a PR?

**Comment by starostin** [comment]
Hi, could you please provide an example how to add failure screenshots to allure? I am getting screenshots by:
`
jasmineNodeOpts: {
    defaultTimeoutInterval: 9999999,
    expectationResultHandler: function(passed, assertion) {
      if (passed) {
        return;
      }
      var title = assertion.message.replace(/\s/g, '-');
      client.saveScreenshot(('assertionError_' + title + '.png'));
    }
  },
`
I looked on your comment to [this code](https://github.com/webdriverio/wdio-allure-reporter/blob/master/lib/reporter.js#L95), but this code return on line 95

**Comment by tortila** [comment]
:+1:

**Comment by SchwaFa** [comment]
Any news on this?

@evrycollin https://www.npmjs.com/package/wdio-allure-addons-reporter looks interessting, but why didn't you add some documentation about how to add screenshots to the allure report? ;)

@Burgi0101 Can you tell us how you solved it with the mentioned allure-addons reporter?

@christian-bromann I think about more than 2 years ago, I was already complaining about missing screenshots in reports from webdriverio. ;) It's a bit sad to see that this is still an issue nowadays.
In my opinion, wdio reports without screenshots attached to them for failing tests are almost useless, because you can't debug why a certain test failed and how the page actually looked like at that moment

**Comment by christian-bromann** [comment]
> It's a bit sad to see that this is still an issue nowadays

I absolutely agree. I find it also sad though that you expect me to fix this issue for you. I don't use the allure reporter and have other priorities in the WebdriverIO project. Please remember that this is an open source project and involvement is required from everyone.

**Comment by SchwaFa** [comment]
Sure, it is an OpenSource project, but since you are the head of it and involved in all discussions (and prioritization) I just wanted to address this. ;)

My question is more: Is there any other wdio reporter that includes screenshots for failing tests? Or how do people work with the test results? (although this is the wrong place to discuss this ;))

**Comment by netmajor** [comment]
@christian-bromann Please close issue

**Comment by rytikovroman1994** [comment]
There was a problem with adding a screenshot if it was in the buffer. Leave the solution here. Maybe someone will come in handy.
```
browser.call(()=> {
                return new Promise((resolve)=>{
                    diff.image.getBuffer(Jimp.AUTO, (err, res) => {
                    resolve(res);
                    });
                })
                .then((res)=>reporter.createAttachment("difference", Buffer.from(res, "base64"), 'image/png'));
            });
```
