### ISSUE TITLE
How to define Steps

### ISSUE THREAD

**Issue by cloudfflies** [webdriverio/wdio-allure-reporter#32]
Hello,

How can I define steps [1] in javascipt and those steps should be on Allure reports?

[1] https://github.com/allure-framework/allure-core/wiki/Steps

**Comment by just-boris** [comment]
Every webdriver.io command is a step.

If you want to define your high-order step, just create a command

```js
browser.addCommand("myStep", () => {
   // perform any actions with browser...
});
```

This command will be recorded as well as any standard one.

**Comment by christian-bromann** [comment]
thanks @just-boris
