### ISSUE TITLE
[mocha] runtime skip (pending case) corrupts Allure report xml

### ISSUE THREAD

**Issue by ninnepinne** [webdriverio/wdio-allure-reporter#34]
If you use this.skip() in a wdio mocha test the report XML will be corrupted.
As a result you can not create the Allure report (you will get infamous Java String error others have reported)

The XML will end up with double test entries of which the original correct test entry will have empty status and timestamp.

The reason for this is according to my investigation the way "allure-js-commons" interface with "wdio-allure-reporter".

When the test case is skipped, the "wdio-allure-reporter" will get an event and handle it this way:
```javascript
this.on('test:pending', (test) => {  
            this.getAllure(test.cid).pendingCase(test.title)   
})
```

And when "allure-js-commons" is called from the line above:
```javascript
Allure.prototype.pendingCase = function(testName, timestamp) {  
    this.startCase(testName, timestamp);  
    this.endCase('pending', {message: 'Test ignored'}, timestamp);  
};
```
...it will start a NEW case even if one was already running.

A run log will look like this:
```javascript
startSuite
startCase
[skip being called in mocha code after runtime check]
[pending event]
startCase <---- wrong
endCase
...
endSuite
```

A very simple fix (to "wdio-allure-reporter") would be:
```javascript
this.on('test:pending', function (test) {
            //_this.getAllure(test.cid).pendingCase(test.title); <--old way
            
            const allure = this.getAllure(test.cid)
            const status = 'pending'

            if (!allure.getCurrentTest()) {
                allure.startCase(test.title)
            } else {
                allure.getCurrentTest().name = test.title
            }
            
            // end steps as on fail?
            while (allure.getCurrentSuite().currentStep instanceof Step) {
                allure.endStep(status)
            }

            allure.endCase(status)
});
```
Effectively bypassing the "allure-js-commons" pendingCase function and instead backtrack and close everything with the pending status.

Perhaps you would want to make changes to "allure-js-commons" instead/too.

**Comment by just-boris** [comment]
Thank you for the detailed bug report! I will take a look.

**Comment by ninnepinne** [comment]
Thanks! 
A gotcha is that this.skip() in mocha does not play nice with arrow functions so use function() in the it().  
I also think you need a very recent version of mocha.

**Comment by jaysirju** [comment]
On a somewhat related not, retrying a failed test also causes the XML corruption that has been reported.

**Comment by netmajor** [comment]
@ninnepinne Do you still have that problem ? I check test in library 
```
    it('should detect pending test cases', () => {
```
```
describe('A pending Suite', () => {
    xit('pending test', () => {
        expect(1).to.equal(1)
    })

    it('test without function')
})
```
And it generate nice xml output.

**Comment by ninnepinne** [comment]
Hi.
Thanks for looking into the matter. I unfortunately do not have access to
the code anymore (switched job), but I think the problem was solved with
Allure2.
At least the report generation process did not crash after that.
Thanks
/F

**Comment by netmajor** [comment]
@christian-bromann Please close ;)
