### ISSUE TITLE
Node JS platform independent html report generator from allure results

### ISSUE THREAD

**Issue by rahulmr** [webdriverio/wdio-allure-reporter#35]
@christian-bromann I have opened [issue](https://github.com/allure-framework/allure1/issues/896) for generating reports from allure results programmatically using Node JS which should be platform independent. Currently, there is a list of generators but none is specific to Node JS. Allure command line does not seem to be platform independent.
Opening this issue just for tracking.

**Comment by just-boris** [comment]
will be resolved at https://github.com/allure-framework/allure1/issues/896
