### ISSUE TITLE
Make use of allure-mocha API 

### ISSUE THREAD

**Issue by Efefefef** [webdriverio/wdio-allure-reporter#37]
Hi guys!
I am using wdio-allure-reporter. Is it possible to somehow define steps, descriptions, severities, etc. in tests?
Similar like in this API for global allure object https://github.com/allure-framework/allure-mocha.
Can I somehow make use of allure-mocha package for getting the augmented result generated with wdio-allure-reporter ?

**Comment by just-boris** [comment]
The architecture of `wdio` is multiprocess. For Allure it means that reporter will be run in the parent process and in the test you will not get an access to `allure` object.

As the easiest way I can only recommend to run Mocha directly and use webdriver.io in [Standalone mode](http://webdriver.io/guide/getstarted/modes.html#Standalone-Mode)

**Comment by christian-bromann** [comment]
> As the easiest way I can only recommend to run Mocha directly and use webdriver.io in Standalone mode

@just-boris With that you would loose all advantages of the testrunner. Why we can't propagate allure events to the parent process?

**Comment by just-boris** [comment]
I was thinking about it. First of all, for tagging tests by features.

First of all, we need to discuss extra API methods that will provide that functionality. It may be something like this

```js
import allure from 'wdio-allure-reporter/runtime';

it('is a test', () => {
  allure.feature('feature name');
  allure.descripton(`
     Test description, with **markdown**
  `);

   browser.url(...).click(...) // your test code
});
```

It is possible but requires extra work of course. Are you okay with the proposed API at least?

**Comment by christian-bromann** [comment]
> Are you okay with the proposed API at least?

Absolutely!

**Comment by just-boris** [comment]
Okay. Will try to do this. Currently, all my available time is taken with finishing things for Allure 2.0, so I can't give any dates.

If somebody else would like to contribute it, I will be happy to help with advice.

**Comment by monolithed** [comment]
Should be linked https://github.com/webdriverio/webdriverio/pull/1893

**Comment by netmajor** [comment]
I am also looking forward for this feature ;)

**Comment by Efefefef** [comment]
@just-boris Hi! Any news about supporting allure features so far?
For me, the most crucial thing is to be able to use 'step' feature. 
So everybody can clearly read on what action test fails, not just have JSON Wire Protocol in logs telling nothing about. Now I have to every time go into the code to the line provided by stacktrace to check what action exactly failing. That kills the ability to have clear vision for other QAs and PMs

**Comment by just-boris** [comment]
I am considering this feature as "pull-requests are welcome".

To be honest, at my work I mostly using `allure-mocha` package and its API, so I don't have a clear vision, how this API should look like.

If anybody wants to have this feature, do not hesitate to submit any code, that shows your expected result. I will help to make the code working.

**Comment by netmajor** [comment]
Hi @just-boris , @christian-bromann , am wanted to support implementation of useful allure APIs which started @jeremypenner but I have problem with running tests in wdio-allure-reporter.

Each test failed like that:
```
Error: ENOENT: no such file or directory, scandir 'C:\Source\wdio-allure-reporter\allure-results'
      at Object.fs.readdirSync (fs.js:910:18)
      at getResultFiles (C:/Source/wdio-allure-reporter/test/helper.js:19:15)
      at getResults (C:/Source/wdio-allure-reporter/test/helper.js:10:12)
      at C:/Source/wdio-allure-reporter/test/helper.js:36:16
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
I have to change allure results folder to 'allure-results' because in windows folders cannot starts with dot.

I run build task with success. Then I create 'allure-results' folder, but test task delete it. Can it be a issue ?

**Comment by netmajor** [comment]
Hi all!
Solution for above problem was proper version of node and npm installed...
After that I use code of @jeremypenner . All tests passed. Now I will try to wrote some new tests for new functionalities. Without that new code not pass review?

**Comment by netmajor** [comment]
Can someone change status to in development ? I will adding new features...

https://github.com/webdriverio/wdio-allure-reporter/pull/59
https://github.com/webdriverio/wdio-allure-reporter/pull/60

**Comment by BorisOsipov** [comment]
it almost done.See docs https://github.com/webdriverio/wdio-allure-reporter#supported-allure-api

**Comment by yuxli066** [comment]
The "createStep" feature does not allow for a call back to define the steps for that particular custom step?

**Comment by BorisOsipov** [comment]
@yuxli066 It does not allow

**Comment by yuxli066** [comment]
@BorisOsipov Is there any possible way to include that feature?

**Comment by BorisOsipov** [comment]
@yuxli066 Unfortunately no. We can work with reporter from your test code only through `subprocess.send({})` [see](https://nodejs.org/api/child_process.html#child_process_subprocess_send_message_sendhandle_options_callback)
(because reporter and tests runs in different processes)

**Comment by yuxli066** [comment]
@BorisOsipov , I see, that really is unfortunate, are there any work arounds that you would like to recommend if I wanted to use this feature?

**Comment by BorisOsipov** [comment]
@yuxli066 see https://github.com/webdriverio/wdio-allure-reporter/issues/37#issuecomment-278339238

**Comment by yuxli066** [comment]
Did you mean this right here ? 
```
import allure from 'wdio-allure-reporter/runtime';

it('is a test', () => {
  allure.feature('feature name');
  allure.descripton(`
     Test description, with **markdown**
  `);

   browser.url(...).click(...) // your test code
});
```
I tried this but it was not working for me @BorisOsipov

**Comment by BorisOsipov** [comment]
no I mean use https://github.com/allure-framework/allure-mocha

**Comment by yuxli066** [comment]
Is there a way to integrate that with the wdio test runner?

**Comment by BorisOsipov** [comment]
no
