### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by gitdaemon** [webdriverio/wdio-allure-reporter#38]
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
c:\tt\webdriverio-sample
+-- wdio-allure-reporter@0.0.2
`-- UNMET PEER DEPENDENCY webdriverio@^4.0.7

npm WARN wdio-screenshot@0.5.0 requires a peer of webdriverio@^4.0.7 but none was installed.
npm WARN wdio-visual-regression-service@0.7.0 requires a peer of webdriverio@^4.0.7 but none was installed.
npm WARN webdriverio-sample No description
npm WARN webdriverio-sample No repository field.
npm WARN webdriverio-sample No license field.

I am getting above error while i install in wdio verion v4.6.2

**Comment by christian-bromann** [comment]
These are warnings. Make sure you have WebdriverIO installed, see
```
UNMET PEER DEPENDENCY webdriverio@^4.0.7
```
