### ISSUE TITLE
Add failure screenshot to report (need help)

### ISSUE THREAD

**Issue by starostin** [webdriverio/wdio-allure-reporter#41]
Hi. I am trying to use jasmine and webdriverio for my project. And also create allure reports. Now I am trying to add screenshots to report, when my test failed. So, for getting screenshots I am using:
`
jasmineNodeOpts: {
    defaultTimeoutInterval: 9999999,
    expectationResultHandler: function(passed, assertion) {
      if (passed) {
        return;
      }
      var title = assertion.message.replace(/\s/g, '-');
      client.saveScreenshot(('assertionError_' + title + '.png'));
    }
  }
`
And it works fine. But how could I add this screenshot to my allure report?
I have found issue about screenshots, and comment to [ the following code](https://github.com/webdriverio/wdio-allure-reporter/blob/master/lib/reporter.js#L95). But I didn't get how could it work. Could you please give me some example? Thanks.

**Comment by christian-bromann** [comment]
please see #25
