### ISSUE TITLE
Failure screenshot hidden away in Execution test body

### ISSUE THREAD

**Issue by psmod2** [webdriverio/wdio-allure-reporter#45]
Hello,

I'm using Allure along with WDIO.

One thing I need help with - for failing tests, the screenshot is hidden in the Execution test body - attaching a screenshot to explain what i mean.

How do i get the screenshot to appear at the top?

![a](https://user-images.githubusercontent.com/15928263/28202483-8242859a-68b0-11e7-8e7a-f122493bcb21.PNG)
![b](https://user-images.githubusercontent.com/15928263/28202482-823d4b5c-68b0-11e7-817d-359e5fdbebfa.PNG)

**Comment by just-boris** [comment]
Hello! Current behavior is defined in our code and cannot be changed on your side.

However we would be happy to accept a PR, that improves functionality about this. The code which is responsible for that feature is around [this line](https://github.com/webdriverio/wdio-allure-reporter/blob/master/lib/reporter.js#L99)

If you have any questions, please let us know!
