### ISSUE TITLE
Tidy capabilities

### ISSUE THREAD

**Issue by psmod2** [webdriverio/wdio-allure-reporter#46]
Hi,

In the current WDIO Allure report, the Environment capabilities are shown as a JSON object `currentTest.addParameter('environment-variable', 'capabilities', JSON.stringify(test.runner[test.cid]));`

Instead of this I'm looking for a tidier version, namely I only want to show the browser options I've passed.

Is it possible to either:

a - disable the capabilities being shown at all (and I could write my own using allures environment.properties file)
or
b - only show selected things

Thanks,

**Comment by christian-bromann** [comment]
This is surely possible. But I don't see how removing information makes any sense. Can you provide more information/screenshots/explanation on this?

**Comment by psmod2** [comment]
Hi,

I just want it to look neater than a big Json 'stringify'. 

So I'd rather have something like capability as just one line from whatever I get from Jenkins. 

Hope that makes sense. 

I agree with your perspective in that all information is ultimately information and of course it causes no harm. However from my side it's for the purpose of a clean looking report. 

Cheers.

**Comment by christian-bromann** [comment]
@psmod2 I guess the best way to move forward is a PR. From your description it is hard to exactly know what you are looking for here. This might be a valuable enhancement but you are the only one who could implement this right. So if you can provide a PR with screenshots and the patch that would be awesome.

Thanks!

**Comment by psmod2** [comment]
Hi - sorry couldny attached screenshot before - here it is now.

This is what I meant by a cluttered JSON string - of course it contains all the info.

![capture](https://user-images.githubusercontent.com/15928263/29105275-c7fd5672-7d06-11e7-9523-5a208bf79f1d.PNG)
