### ISSUE TITLE
Steps in wdio-allure reporter

### ISSUE THREAD

**Issue by GenadyMgr** [webdriverio/wdio-allure-reporter#49]
Hi all,

I'm using wdio-allure reporter, i have an issue that all the steps in the report are post/get of the webdriver.

how can i give custom names for the steps? (maybe some thing like @Step in java annotations or allure.createStep).

thanks a lot :)

**Comment by just-boris** [comment]
There already a PR towards implementing this functionality: https://github.com/webdriverio/wdio-allure-reporter/pull/39

Unfortunately the person started doing this does not respond anymore. And I also do not have enough time to finish this. 

If you really lack that feature, you can help our and finish that work, contributing one more PR based on that changes.

**Comment by christian-bromann** [comment]
Let's continue convo in #39
