### ISSUE TITLE
Broken tests cancel further test cases

### ISSUE THREAD

**Issue by michaelDomingues** [webdriverio/wdio-allure-reporter#6]
Hi,

When Allure tags a test as broken, those which follow are not accepted as suitable for the reports. 
I think this shouldn't be this way for a broken test, only failure situations.

**Comment by just-boris** [comment]
You meant that if some test is broken, you want not to go on running this suite?

I think that it shouldn't  be a default behavior, but you can set up your tests in that way if you want.

**Comment by michaelDomingues** [comment]
No I mean, if you have 

```
suite('XPTO')
     testA()
     testB()
     testC()
     testD()
```

and <testB> is considered **broken**, remaining test suite should be executed and reported!
In this case, allure would report until <testB>

**Comment by just-boris** [comment]
Well, then it looks like a bug. In my simple case, it works well.

```
it('1st test', () => {
    browser.url('http://example.com');
});

it('2nd test [should break]', () => {
     throw new Error('let it be broken');
});

it('3rd test', () => {
    browser.url('http://google.com');
});
```

I got all 3 tests in the report. How do your tests look like?

**Comment by michaelDomingues** [comment]
weird... I can't get that results.

My suite is pretty much the same as yours but 1st test and 3rd test are basically elements discovery and interaction.
Test 2 is a HTTP lib usage to capture all requests from a click in an element. That lib is [webdriverajax](https://www.npmjs.com/package/webdriverajax).

Most of the times, I got my requests and answers but allure considers the test as broken.

**Comment by christian-bromann** [comment]
@michaelDomingues what's the state of this issue? Is this still happening for you?

**Comment by michaelDomingues** [comment]
Yeah, still happening.. Tests are executed but not triggered in allure.

A seg, 4/04/2016, 18:36, Christian Bromann <notifications@github.com>
escreveu:

**Comment by christian-bromann** [comment]
> If so could you try to create a minimal reproducible example?

@michaelDomingues

**Comment by christian-bromann** [comment]
@michaelDomingues should be fixed with the recent released version
