### ISSUE TITLE
Using allure2-js-commons

### ISSUE THREAD

**Issue by netmajor** [webdriverio/wdio-allure-reporter#62]
Latest allure-js-commons are using allure1 model (xml files).
Allure team are working on new version of js-commons that will store files in json format.
see https://github.com/korobochka/allure2-js-commons

We should move to allure2 to be up to date...

**Comment by just-boris** [comment]
> We should move to allure2 to be up to date...

I would not say, that this is the right time to do that. The new package at the very early stage of development and is not used by a lot of people.

As soon as will be more stable, it will become available under the original name `allure-js-commons`. Before that I would not recommend to do any changes.

**Comment by netmajor** [comment]
I agree with you. I have created this issue rather as feature for future. I don't have access right to add labels.

Now I myself start to add allure api methods to project. I also want to look into issues and fix if is possible.

Maybe then I create next fork where I will try to use allure2-js-commons. I think that it will be great to support allure team in their work. If we don't try to use it they don't know that their code could contains bugs...
