### ISSUE TITLE
Duplicate screenshot attachments

### ISSUE THREAD

**Issue by dannyjhall** [webdriverio/wdio-allure-reporter#80]
As discussed on #58, screenshot attachments are now duplicated due to the addition of the new `runner:screenshot` listener.

> As @BorisOsipov mentioned earlier, screenshot attachments were already handled when browser.saveScreenshot() was called: https://github.com/webdriverio/wdio-allure-reporter/blob/master/lib/reporter.js#L99
 Screenshots are now attached to the report twice, first via the existing runner:result listener and again with the new runner:screenshot listener.

<img width="274" alt="35269994-9a3f6412-0025-11e8-9a0f-7c95db2111ff" src="https://user-images.githubusercontent.com/1398186/35326300-240b3356-00ee-11e8-812b-b96567c2ca6c.png">

> To fix this either the new runner:screenshot listener should be removed, or if we want to keep it, the screenshot command in runner:result needs to be ignored so the command body doesn't get attached to the report as a json response.
I'd be happy to create a PR for this if required?

**Comment by christian-bromann** [comment]
Fixed in #81
