### ISSUE TITLE
'Multi-browser test case' fails on Windows

### ISSUE THREAD

**Issue by BorisOsipov** [webdriverio/wdio-allure-reporter#83]
https://github.com/webdriverio/wdio-allure-reporter/blob/e3469fab3c945fc8ee3b3c52a340cf032687b1ce/test/specs/test-case-multi-browser.js#L19

Fails with:

> 1) Multi-browser test case
>        should detect different browsers parameter for same test case:
>      AssertionError: expected '["C:\\\\wdio-allure-reporter\\\\test\\\\fixtures\\\\specs\\\\test-case-multi-browser.js"]' to include 'test/fixtures/specs/test-case-multi-browser.js'
>       at C:/Temp/wdio-allure-reporter/test/specs/test-case-multi-browser.js:19:92
>       at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by netmajor** [comment]
Ok. I will fix it. I need to check only file name

**Comment by netmajor** [comment]
@BorisOsipov  Done. Could you check now ?

**Comment by christian-bromann** [comment]
This passes now, thanks @netmajor
