### ISSUE TITLE
Jasmine - when using 'xit' for and 'it' block to skip a test, status is marked as 'undefined' not 'skipped'

### ISSUE THREAD

**Issue by matt-mcc1** [webdriverio/wdio-allure-reporter#95]
In a Jasmine spec, when you xit an 'it' block to skip it, and run the tests, wdio-allure-reporter marks the status of that case to be 'undefined' which then results in a allure-commandline exception. 

Would expect the status in the output XML to be 'skipped' not 'undefined'. 

Dot reporter correctly states 'skipped'. 

`<test-case start='1519520826265' status='undefined'>`

Let me know if any more info is needed

Versions:
wdio: v4.10.2
wdio-allure-reporter@0.3.2
allure-js-commons@1.3.1
wdio-jasmine-framework@0.3.2

**Comment by matt-mcc1** [comment]
var assert = require('assert');

describe('webdriver.io page', function() {

    it('should have the right title - the fancy generator way', function () {
        browser.url('http://webdriver.io');
        var title = browser.getTitle();
        assert.equal(title, 'Fake assertion to fail a test intentionally');
    });

    xit('should have the right title - the fancy generator way', function () {
        browser.url('http://webdriver.io');
        var title = browser.getTitle();
        assert.equal(title, 'Fake assertion to fail a test intentionally');
    });
});

**Comment by BorisOsipov** [comment]
@matt-mcc1 ok. thanks. I will have look.

**Comment by BorisOsipov** [comment]
I don't find isue root cause.
It is wdio-jasmine specific - it reports pending test strange. I am not jasmine user and won't plane fix this issue.

I've added correponding test https://github.com/BorisOsipov/wdio-allure-
reporter/commit/3aabc5ee12f3acc7d32d21c2ee1daa9f0772ba50#diff-45cbff1fc84c9e99630fd43f571f49eeR43
It may help to fix issue somehow.

**Comment by matt-mcc1** [comment]
Thanks @BorisOsipov 
I've just retested with latest version of wdio-allure-reporter. 

For a Jasmine xit , I'm still getting status='undefined'.

Having said that, in the Allure report they are marked as 'Unknown' when generated using latest Allure Commandline 2.5.0. Previously I was getting report generation exceptions. 

@christian-bromann  - shall I raise a ticket on wdio-jasmine repo?

**Comment by matt-mcc1** [comment]
Could be similar to https://github.com/webdriverio/wdio-jasmine-framework/issues/29

**Comment by BorisOsipov** [comment]
@matt-mcc1 We have fixed jasmine pending case reporting.

Have a look and provide feedback for us. @christian-bromann will release new version soon.
